name: "SX1302 LoRa Gateway"
version: "1.2.2"
slug: sx1302_gateway_ha
description: "Home Assistant add-on for SX1302 LoRa Gateway."
arch: ["aarch64", "armv7", "armhf"]
startup: application
boot: auto

options:
  gateway_id: "AA555A0000000000"
  server_address: "127.0.0.1"
  port: 1700
  region: "EU868"  # Default region
  reset_pin: 17  # Default reset pin
  power_en_pin: 18  # Default power enable pin
  gps: "ttyAMA10"

schema:
  gateway_id: "str"
  server_address: "str"
  port: "int"
  region: "list(EU868|US915|AS923|AU915|CN470)"  # Lista delle regioni supportate
  reset_pin: "int"
  power_en_pin: "int"
  gps: "str"

ports:
  8080/tcp: null  #Healthcheck port

watchdog: "http://[HOST]:[PORT:8080]/health"

init: false

gpio: true
uart: true

devices:
  - "/dev/spidev0.0"
  - "/dev/spidev0.1"
  - "/dev/gpiomem"
  - "/dev/i2c-1"
  - "/dev/ttyAMA0"
  - "/dev/ttyAMA10"
  - "/dev/ttyS0"
